version: '3.9'

services:
  webssh-vscode-dev:
    build:
      context: ./
      dockerfile: Dockerfile_dev
    container_name: webssh-vscode
    volumes:
        - './:/workspace'
    stdin_open: true
    tty: true